# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: corepack enable
      - run: pnpm install
      - run: pnpm test
      - uses: codecov/codecov-action@v2.1.0
        with:
          # Directory to search for coverage reports.
          directory: coverage
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          flags: unittests
          # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: true
          # Specify whether the Codecov output should be verbose
          verbose: true
